'use strict'

# provinces = [
# 	{_id: 1, province: "Sài Gòn", short_name: "SG"},
# 	{_id: 2, province: "Kon Tum", short_name: "KT"},
# 	{_id: 3, province: "Gia Lai", short_name: "GL"},
# 	{_id: 4, province: "Đăk Lăk", short_name: "ĐL"},
# 	{_id: 5, province: "Đăk Nông", short_name: "ĐN"},
# 	{_id: 6, province: "Lâm Đồng", short_name: "LĐ"},
# 	{_id: 7, province: "Đà Nẵng", short_name: "ĐN"}]

provinces = [
	{_id: 1, province: "TP HCM", short_name: ""},
	{_id: 2, province: "Hà Nội", short_name: ""},
	{_id: 3, province: "Đà Nẵng", short_name: ""},
	{_id: 4, province: "Đắk Lắk", short_name: ""},
	{_id: 5, province: "Cần Thơ", short_name: ""},
	{_id: 6, province: "An Giang", short_name: ""},
	{_id: 7, province: "Bà Rịa - Vũng Tàu", short_name: ""},
	{_id: 8, province: "Bắc Giang", short_name: ""},
	{_id: 9, province: "Bắc Kạn", short_name: ""},
	{_id: 10, province: "Bạc Liêu", short_name: ""},
	{_id: 11, province: "Bắc Ninh", short_name: ""},
	{_id: 12, province: "Bến Tre", short_name: ""},
	{_id: 13, province: "Bình Định", short_name: ""},
	{_id: 14, province: "Bình Dương", short_name: ""},
	{_id: 15, province: "Bình Phước", short_name: ""},
	{_id: 16, province: "Bình Thuận", short_name: ""},
	{_id: 17, province: "Cà Mau", short_name: ""},
	{_id: 18, province: "Cao Bằng", short_name: ""},
	{_id: 19, province: "Đắk Nông", short_name: ""},
	{_id: 20, province: "Điện Biên", short_name: ""},
	{_id: 21, province: "Đồng Nai", short_name: ""},
	{_id: 22, province: "Đồng Tháp", short_name: ""},
	{_id: 23, province: "Gia Lai", short_name: ""},
	{_id: 63, province: "Hà Giang", short_name: ""},
	{_id: 24, province: "Hà Nam", short_name: ""},
	{_id: 25, province: "Hà Tĩnh", short_name: ""},
	{_id: 26, province: "Hải Dương", short_name: ""},
	{_id: 27, province: "Hậu Giang", short_name: ""},
	{_id: 28, province: "Hòa Bình", short_name: ""},
	{_id: 29, province: "Hưng Yên", short_name: ""},
	{_id: 30, province: "Hải Phòng", short_name: ""},
	{_id: 31, province: "Khánh Hòa", short_name: ""},
	{_id: 32, province: "Kiên Giang", short_name: ""},
	{_id: 33, province: "Kon Tum", short_name: ""},
	{_id: 34, province: "Lai Châu", short_name: ""},
	{_id: 35, province: "Lâm Đồng", short_name: ""},
	{_id: 36, province: "Lạng Sơn", short_name: ""},
	{_id: 37, province: "Lào Cai", short_name: ""},
	{_id: 38, province: "Long An", short_name: ""},
	{_id: 39, province: "Nam Định", short_name: ""},
	{_id: 40, province: "Nghệ An", short_name: ""},
	{_id: 41, province: "Ninh Bình", short_name: ""},
	{_id: 42, province: "Ninh Thuận", short_name: ""},
	{_id: 43, province: "Phú Thọ", short_name: ""},
	{_id: 44, province: "Phú Yên", short_name: ""},
	{_id: 45, province: "Quảng Bình", short_name: ""},
	{_id: 46, province: "Quảng Nam", short_name: ""},
	{_id: 47, province: "Quảng Ngãi", short_name: ""},
	{_id: 48, province: "Quảng Ninh", short_name: ""},
	{_id: 49, province: "Quảng Trị", short_name: ""},
	{_id: 50, province: "Sóc Trăng", short_name: ""},
	{_id: 51, province: "Sơn La", short_name: ""},
	{_id: 52, province: "Tây Ninh", short_name: ""},
	{_id: 53, province: "Thái Bình", short_name: ""},
	{_id: 54, province: "Thái Nguyên", short_name: ""},
	{_id: 55, province: "Thanh Hóa", short_name: ""},
	{_id: 56, province: "Thừa Thiên Huế", short_name: ""},
	{_id: 57, province: "Tiền Giang", short_name: ""},
	{_id: 58, province: "Trà Vinh", short_name: ""},
	{_id: 59, province: "Tuyên Quang", short_name: ""},
	{_id: 60, province: "Vĩnh Long", short_name: ""},
	{_id: 61, province: "Vĩnh Phúc", short_name: ""},
	{_id: 62, province: "Yên Bái", short_name: ""}]


get_all = ->
	return provinces

module.exports = {
	get_all
}
